<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            // Tubérculos
            [
                'nombre' => 'Papa Holandesa',
                'descripcion' => 'Papa holandesa fresca del Valle, ideal para freír y hornear.',
                'codigo_barras' => 'PAPA001',
                'precio' => 8.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'tuberculos',
                'stock' => 100,
                'stock_minimo' => 20,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addMonths(2),
            ],
            [
                'nombre' => 'Papa Waycha',
                'descripcion' => 'Papa waycha del altiplano, perfecta para sopas y guisos.',
                'codigo_barras' => 'PAPA002',
                'precio' => 6.50,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'tuberculos',
                'stock' => 80,
                'stock_minimo' => 15,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addMonths(2),
            ],
            [
                'nombre' => 'Yuca Fresca',
                'descripcion' => 'Yuca fresca de los valles cruceños.',
                'codigo_barras' => 'YUCA001',
                'precio' => 5.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'tuberculos',
                'stock' => 60,
                'stock_minimo' => 10,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(2),
            ],

            // Verduras
            [
                'nombre' => 'Choclo Fresco',
                'descripcion' => 'Choclo tierno recién cosechado, ideal para sopas y humitas.',
                'codigo_barras' => 'CHOCLO001',
                'precio' => 3.00,
                'peso' => 0.5,
                'unidad_medida' => 'unidad',
                'categoria' => 'verduras',
                'stock' => 150,
                'stock_minimo' => 30,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(1),
            ],
            [
                'nombre' => 'Tomate Perita',
                'descripcion' => 'Tomate perita fresco del Valle de los Yungas.',
                'codigo_barras' => 'TOMATE001',
                'precio' => 12.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'verduras',
                'stock' => 50,
                'stock_minimo' => 10,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(1),
            ],
            [
                'nombre' => 'Cebolla Blanca',
                'descripcion' => 'Cebolla blanca fresca de Cochabamba.',
                'codigo_barras' => 'CEBOLLA001',
                'precio' => 7.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'verduras',
                'stock' => 70,
                'stock_minimo' => 15,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addMonths(1),
            ],
            [
                'nombre' => 'Zanahoria',
                'descripcion' => 'Zanahoria fresca y crujiente del Valle.',
                'codigo_barras' => 'ZANAHORIA001',
                'precio' => 6.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'verduras',
                'stock' => 60,
                'stock_minimo' => 12,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(3),
            ],
            [
                'nombre' => 'Locoto Rojo',
                'descripcion' => 'Locoto rojo picante para salsas tradicionales.',
                'codigo_barras' => 'LOCOTO001',
                'precio' => 15.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'verduras',
                'stock' => 30,
                'stock_minimo' => 5,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(2),
            ],

            // Frutas
            [
                'nombre' => 'Naranja de Bermejo',
                'descripcion' => 'Naranjas dulces y jugosas de Bermejo.',
                'codigo_barras' => 'NARANJA001',
                'precio' => 10.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'frutas',
                'stock' => 80,
                'stock_minimo' => 15,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(2),
            ],
            [
                'nombre' => 'Plátano de Yungas',
                'descripcion' => 'Plátano guineo fresco de los Yungas.',
                'codigo_barras' => 'PLATANO001',
                'precio' => 8.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'frutas',
                'stock' => 90,
                'stock_minimo' => 20,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(1),
            ],
            [
                'nombre' => 'Mandarina',
                'descripcion' => 'Mandarina dulce de temporada.',
                'codigo_barras' => 'MANDARINA001',
                'precio' => 12.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'frutas',
                'stock' => 50,
                'stock_minimo' => 10,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(2),
            ],

            // Granos
            [
                'nombre' => 'Arroz Grano de Oro',
                'descripcion' => 'Arroz de primera calidad, grano largo.',
                'codigo_barras' => 'ARROZ001',
                'precio' => 9.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'granos',
                'stock' => 200,
                'stock_minimo' => 50,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addYear(),
            ],
            [
                'nombre' => 'Quinua Real',
                'descripcion' => 'Quinua real del altiplano boliviano.',
                'codigo_barras' => 'QUINUA001',
                'precio' => 25.00,
                'peso' => 0.5,
                'unidad_medida' => 'kg',
                'categoria' => 'granos',
                'stock' => 40,
                'stock_minimo' => 10,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addYear(),
            ],
            [
                'nombre' => 'Maíz Pelado',
                'descripcion' => 'Maíz pelado para mote y sopas.',
                'codigo_barras' => 'MAIZ001',
                'precio' => 8.00,
                'peso' => 1.0,
                'unidad_medida' => 'kg',
                'categoria' => 'granos',
                'stock' => 60,
                'stock_minimo' => 15,
                'activo' => true,
                'destacado' => false,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addMonths(6),
            ],

            // Huevos
            [
                'nombre' => 'Huevos de Campo',
                'descripcion' => 'Huevos de gallinas criadas al aire libre, 30 unidades.',
                'codigo_barras' => 'HUEVO001',
                'precio' => 35.00,
                'peso' => 1.5,
                'unidad_medida' => 'maple',
                'categoria' => 'huevos',
                'stock' => 25,
                'stock_minimo' => 5,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addWeeks(3),
            ],

            // Miel
            [
                'nombre' => 'Miel Pura de Abeja',
                'descripcion' => 'Miel pura de abeja de los Yungas, 500ml.',
                'codigo_barras' => 'MIEL001',
                'precio' => 40.00,
                'peso' => 0.5,
                'unidad_medida' => 'frasco',
                'categoria' => 'miel',
                'stock' => 20,
                'stock_minimo' => 5,
                'activo' => true,
                'destacado' => true,
                'lote' => 'LOTE-' . date('Ymd'),
                'fecha_vencimiento' => now()->addYear(),
            ],
        ];

        foreach ($productos as $producto) {
            Producto::create($producto);
        }
    }
}
